// Copyright 10-Jul-2019 ºDeme
// GNU General Public License - V3 <http://www.gnu.org/licenses/>

#include "tpls/exercise.h"

char *exercise_html (char *unit_key, char *exer_key) {
  return str_f(
    "<!doctype html>\n"
    "<html>\n"
    "<head>\n"
    "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n"
    "<meta http-equiv=\"Pragma\" content=\"no-cache\" />\n"
    "<meta name=\"lang\" content=\"es\" />\n"
    "<meta name=\"author\" content=\"ºDeme.\" />\n"
    "<link rel=\"icon\" type=\"image/png\" href=\"../../../../img/favicon.png\" />\n"
    "<link rel=\"stylesheet\" href=\"../../../../styles.css\" type=\"text/css\" />\n"
    "<script type=\"text/x-mathjax-config\">\n"
    "  MathJax.Hub.Config({\n"
    "    tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]},\n"
    "    SVG: {scale: 83}\n"
    "  });\n"
    "</script>\n"
    "<script type=\"text/javascript\" async\n"
    "  src=\"../../../../MathJax/MathJax.js?config=TeX-AMS-MML_SVG\"></script>\n"
    "<script type=\"text/javascript\" src=\"../../../../libsci.js\"></script>\n"
    "<script type=\"text/javascript\" src=\"../../../globals.js\"></script>\n"
    "<script type=\"text/javascript\" src=\"../../book.js\"></script>\n"
    "<script type=\"text/javascript\">\n"
    "  const unit = \"%s\";\n"
    "  const exercise = \"%s\";\n"
    "</script>\n"
    "\n"
    "<script type=\"text/javascript\">\n"
    "function calculate () {\n"
    "\n"
    "  // ______________\n"
    "  // Start calculus\n"
    "  // ¨¨¨¨¨¨¨¨¨¨¨¨¨¨\n"
    "\n"
    "  let defs = mathJaxInit();\n"
    "  defs += ndef (\"IA\", 3 - 2/3 + 5/6, 6);\n"
    "  defs += ndef (\"IB\", 5/4 - 2/3 * (5/6), 6);\n"
    "  defs += ndef (\"IC\", 4/3 / (8/5 - 7), 6);\n"
    "  defs += ndef (\"ID\", 4/3 * (5/6 - 2 + 3/8), 6);\n"
    "  html(\"DEFS\", defs);\n"
    "\n"
    "  // ____________\n"
    "  // End calculus\n"
    "  // ¨¨¨¨¨¨¨¨¨¨¨¨\n"
    "\n"
    "  MathJax.Hub.Typeset();\n"
    "}\n"
    "\n"
    "window.onload = () => {\n"
    "  divs();\n"
    "  calculate();\n"
    "  $(\"SOL_LINK\").onclick = () => {\n"
    "    MathJax.Hub.Typeset();\n"
    "    $(\"SOL\").style = \"visibility:visible\";\n"
    "  };\n"
    "};\n"
    "</script>\n"
    "\n"
    "</head>\n"
    "<body>\n"
    "\n"
    "<span id=\"DEFS\" style=\"visibility:hidden\"></span>\n"
    "<div id=\"HEADER\"></div>\n"
    "\n"
    "<!-- _____________ -->\n"
    "<!-- Start problem -->\n"
    "<!-- ¨¨¨¨¨¨¨¨¨¨¨¨¨ -->\n"
    "\n"
    "<p>Calcula:</p>\n"
    "<ol type=\"a\">\n"
    "  <li style=\"margin-bottom:4px\"><div class=\"fm2\">\n"
    "      $3 - \\DS {2 \\over 3} + \\DS {5 \\over 6}$\n"
    "  <div></li>\n"
    "</ol>\n"
    "\n"
    "<!-- ___________ -->\n"
    "<!-- End problem -->\n"
    "<!-- ¨¨¨¨¨¨¨¨¨¨¨ -->\n"
    "\n"
    "<p><span id=\"SOL_LINK\" class=\"link\" style=\"cursor:pointer;\">Solución</span></p>\n"
    "<!-- *********************************************************************** -->\n"
    "<div id=\"SOL\" style=\"visibility:hidden\">\n"
    "\n"
    "<!-- ______________ -->\n"
    "<!-- Start solution -->\n"
    "<!-- ¨¨¨¨¨¨¨¨¨¨¨¨¨¨ -->\n"
    "\n"
    "<ol type=\"a\">\n"
    "  <li>$\\IA$</li>\n"
    "</ol>\n"
    "\n"
    "<!-- ____________ -->\n"
    "<!-- End solution -->\n"
    "<!-- ¨¨¨¨¨¨¨¨¨¨¨¨ -->\n"
    "\n"
    "</div>\n"
    "\n"
    "</body>\n"
    "</html>\n",
    unit_key,
    exer_key
  );

}
