// Copyright 10-Jul-2019 ºDeme
// GNU General Public License - V3 <http://www.gnu.org/licenses/>

#include "tpls/unit.h"

char *unit_html (char *unit_key) {
  return str_f(
    "<!doctype html>\n"
    "<html>\n"
    "<head>\n"
    "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n"
    "<meta http-equiv=\"Pragma\" content=\"no-cache\" />\n"
    "<meta name=\"lang\" content=\"es\" />\n"
    "<meta name=\"author\" content=\"ºDeme.\" />\n"
    "<link rel=\"icon\" type=\"image/png\" href=\"../../img/favicon.png\" />\n"
    "<link rel=\"stylesheet\" href=\"../../styles.css\" type=\"text/css\" />\n"
    "<script type=\"text/x-mathjax-config\">\n"
    "  MathJax.Hub.Config({\n"
    "    tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]},\n"
    "    SVG: {scale: 83}\n"
    "  });\n"
    "</script>\n"
    "<script type=\"text/javascript\" async\n"
    "  src=\"../../MathJax/MathJax.js?config=TeX-AMS-MML_SVG\"></script>\n"
    "<script type=\"text/javascript\" src=\"../../libsci.js\"></script>\n"
    "<script type=\"text/javascript\" src=\"../globals.js\"></script>\n"
    "<script type=\"text/javascript\" src=\"book.js\"></script>\n"
    "<script type=\"text/javascript\">\n"
    "  const unit = \"%s\";\n"
    "  const exercise = null;\n"
    "</script>\n"
    "\n"
    "<script type=\"text/javascript\">\n"
    "function calculate () {\n"
    "\n"
    "  // ______________\n"
    "  // Start calculus\n"
    "  // ¨¨¨¨¨¨¨¨¨¨¨¨¨¨\n"
    "\n"
    "  let defs = mathJaxInit();\n"
    "//      defs += ndef (\"WEIGHT\", weight, 0);\n"
    "  html(\"DEFS\", defs);\n"
    "\n"
    "  // ____________\n"
    "  // End calculus\n"
    "  // ¨¨¨¨¨¨¨¨¨¨¨¨\n"
    "\n"
    "  MathJax.Hub.Typeset();\n"
    "}\n"
    "\n"
    "window.onload = () => {\n"
    "  divs();\n"
    "  calculate();\n"
    "};\n"
    "</script>\n"
    "\n"
    "</head>\n"
    "<body>\n"
    "\n"
    "<span id=\"DEFS\" style=\"visibility:hidden\"></span>\n"
    "<div id=\"HEADER\"></div>\n"
    "<div id=\"PG_INDEX\"></div>\n"
    "\n"
    "<!----------------------------------------------------------------------------->\n"
    "<!-- START TEXT --------------------------------------------------------------->\n"
    "<!----------------------------------------------------------------------------->\n"
    "\n"
    "<!--______________________-->\n"
    "<h2>Los números racionales</h2>\n"
    "<!--¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨-->\n"
    "\n"
    "<h3>Números Naturales</h3>\n"
    "<div class=fm>\n"
    "$\\mathbb{N} = \\{0, 1, 2, 3, ...\\}$\n"
    "</div>\n"
    "\n"
    "<!----------------------------------------------------------------------------->\n"
    "<!-- END TEXT ----------------------------------------------------------------->\n"
    "<!----------------------------------------------------------------------------->\n"
    "\n"
    "<div id=\"EXERCISES\"></div>\n"
    "\n"
    "<div style=\"position: fixed;bottom: 0px;right: 10px;cursor: pointer;\">\n"
    "  <span onclick=\"location.assign('#');\">\n"
    "    <img border=\"0\" src=\"../../img/up.png\" alt=\"\" />\n"
    "  </span>\n"
    "</div>\n"
    "<div style=\"position: fixed;top: 0px;right: 10px;cursor: pointer;\">\n"
    "  <span onclick=\"location.assign('#END_PAGE');\">\n"
    "    <img border=\"0\" src=\"../../img/down.png\" alt=\"\" />\n"
    "  </span>\n"
    "</div>\n"
    "\n"
    "<div id=\"END_PAGE\"></div>\n"
    "</body>\n"
    "</html>\n",
    unit_key
  );
}

