static double math_abs (double n);
static int math_digits (char *s);
static int math_eq (double n1, double n2);
static int math_eq_gap (double n1, double n2, double gap);
static Arrf *math_from_en (char *s);
static Arri *math_from_hex (char *s);
static Arrf *math_from_iso (char *s);
static char *math_ftos (double n);
static char *math_ftos2 (double n, int scale);
static char *math_itos (int64_t n);
static double math_max (double n1, double n2);
static double math_min (double n1, double n2);
static double math_pow10 (int64_t ex);
static double math_rnd (void);
static int64_t math_rndi (int64_t top);
static double math_round (double n, int64_t scale);
static Arrf *math_stof (char *s);
static Arri *math_stoi (char *s);
static Arri *math_stoi_base (char *s, int base);
