static void sys_assert (int value, char *pos);
static Arrs *sys_cmd (char *c, Arrs *params);
static Arrs *sys_environ(void);
static char *sys_get_locale (void);
static char *sys_home (void);
static void sys_printb (int v);
static void sys_printi (int64_t v);
static void sys_printf (double v);
static void sys_prints (char *v);
static void sys_printI (Arri *v);
static void sys_printF (Arrf *v);
static void sys_printS (Arrs *v);
static void sys_printD (Arrs *v);
static void sys_print_errorb (int v);
static void sys_print_errori (int64_t v);
static void sys_print_errorf (double v);
static void sys_print_errors (char *v);
static void sys_print_errorI (Arri *v);
static void sys_print_errorF (Arrf *v);
static void sys_print_errorS (Arrs *v);
static void sys_print_errorD (Arrs *v);
static void sys_printlnb (int v);
static void sys_printlni (int64_t v);
static void sys_printlnf (double v);
static void sys_printlns (char *v);
static void sys_printlnI (Arri *v);
static void sys_printlnF (Arrf *v);
static void sys_printlnS (Arrs *v);
static void sys_printlnD (Arrs *v);
static char *sys_read_line (void);
static void sys_set_locale (char * lang);
static void sys_sleep (int64_t millis);
static void sys_testb (int v1, int v2, char *pos);
static void sys_testi (int64_t v1, int64_t v2, char *pos);
static void sys_testf (double v1, double v2, char *pos);
static void sys_tests (char *v1, char *v2, char *pos);
static void sys_testo (Obj *v1, Obj *v2, char *pos);
static void sys_testI (Arri *v1, Arri *v2, char *pos);
static void sys_testF (Arrf *v1, Arrf *v2, char *pos);
static void sys_testS (Arrs *v1, Arrs *v2, char *pos);
static void sys_testD (Arrs *v1, Arrs *v2, char *pos);
static void sys_throw (char *fn, char *msg, char *pos);
static void sys_used(void);
static char *sys_user (void);
