
// INTERFACE ----------------------------------------

#define EXC_KUTT EXC_GENERIC
typedef union built_Val Val;
typedef struct __arr_Varr Varr;
union built_Val {
int b;
int64_t i;
double f;
char *s;
Varr *a;
void *o;
};
struct __arr_Varr {
Val *begin;
Val *end;
Val *end_bf;
};

void ___built_jump (int reference);
char *___built_mpos(char *module_ln);
char *___built_stack_line (char *e);
Val ___built_divi(char *pos, Val n1, Val n2);
Val ___built_divf(char *pos, Val n1, Val n2);
Val ___built_eq (Val type, Val value1, Val value2);
Val ___built_to_str_trace (Val type, Val value);
Val ___built_to_str (Val type, Val value);
void ___built_throw (char *pos, Val msg);
void ___built_trace (Val isComplete, char *pos, Val type, Val value);

Val __arr_all (Val a, Val fn);
Val __arr_any (Val a, Val fn);
void __arr_cat (Val a, Val a2);
Val __arr_cat2 (Val a, Val a2);
void __arr_clear (Val a);
Val __arr_copy (Val a);
Val __arr_drop (Val a, Val n);
Val __arr_dropWhile (Val a, Val fn);
Val __arr_duplicates (Val a, Val fn);
void __arr_each (Val a, Val fn);
void __arr_eachIx (Val a, Val fn);
Val __arr_filter (Val a, Val fn);
void __arr_filterIn (Val a, Val fn);
Val __arr_find (Val a, Val fn);
Val __arr_fromIter (Val it);
Val __arr_fromJs (Val s, Val fn);
Val __arr_from_sarr (Arr *a);
Val __arr_get (Val a, Val ix);
Val __arr_get2 (char *pos, Val a, Val ix);
Val __arr_index (Val a, Val fn);
void __arr_insert (char *pos, Val a, Val ix, Val e);
void __arr_insertArr (char *pos, Val a, Val ix, Val other);
void __arr_insertRange (char *pos, Val a, Val ix, Val other, Val begin, Val end);
Val __arr_join(Val a, Val sep);
Val __arr_map(Val a, Val fn);
Val __arr_new (void);
Val __arr_new_fill (Val el, Val n);
Val __arr_new_from_carr (Val n, Val *els);
Val __arr_peek (char *pos, Val a);
Val __arr_pop (char *pos, Val a);
void __arr_push (Val a, Val el);
Val __arr_reduce (Val a, Val seed, Val fn);
Val __arr_remove (char *pos, Val a, Val ix);
Val __arr_removeRange (char *pos, Val a, Val begin, Val end);
Val __arr_reverse (Val a);
void __arr_reverseIn (Val a);
void __arr_set (Val a, Val ix, Val el);
void __arr_set2 (char *pos, Val a, Val ix, Val el);
void __arr_setArr (char *pos, Val a, Val ix, Val other);
void __arr_setRange (char *pos, Val a, Val ix, Val other, Val begin, Val end);
Val __arr_shift (char *pos, Val a);
void __arr_shuffle (Val a);
Val __arr_size (Val a);
void __arr_sort (Val a, Val fn);
Val __arr_sub (Val a, Val begin, Val end);
Val __arr_sub0 (Val a, Val begin);
Val __arr_take (Val a, Val n);
Val __arr_takeWhile (Val a, Val fn);
Val __arr_toIter (Val a);
Val __arr_toJs (Val a, Val fn);
Arr *__arr_to_sarr (Val a);
void __arr_unshift (Val a, Val e);
Val __arr_unzip (Val a);
Val __arr_unzip3 (Val a);
Val __arr_zip (Val a1, Val a2);
Val __arr_zip3 (Val a1, Val a2, Val a3);

Val __b64_decode (char *pos, Val b64);
Val __b64_decodeBytes (char *pos, Val b64);
Val __b64_encode (Val s);
Val __b64_encodeBytes (Val s);

Val __bytes_add (Val bs1, Val bs2);
Val __bytes_drop (Val bs, Val begin);
Val __bytes_fromArr (Val a);
Val __bytes_fromStr (Val str);
Val __bytes_get (char *pos, Val bs, Val ix);
Val __bytes_new (Val size);
void __bytes_set (char *pos, Val bs, Val ix, Val byte);
Val __bytes_size (Val bs);
Val __bytes_take (Val bs, Val end);
Val __bytes_toArr (Val bs);
Val __bytes_toStr (Val bs);

Val __cryp_decode (Val k, Val c);
Val __cryp_decodeBytes (Val k, Val c);
Val __cryp_encode (Val k, Val tx);
Val __cryp_encodeBytes (Val k, Val bs);
Val __cryp_genK (Val lg);
Val __cryp_key (Val s, Val lg);

Val __dic_copy (Val d);
Val __dic_fromArr (Val a);
Val __dic_fromIter (Val it);
Val __dic_fromJs (Val s, Val fn);
Val __dic_from_smap (Map *m);
Val __dic_get(Val d, Val key);
Val __dic_get2(char *pos, Val d, Val key);
Val __dic_hasKey(Val d, Val key);
Val __dic_keys (Val d);
Val __dic_map (Val d, Val fn);
Val __dic_new_from_carr (Val n, Val *els);
void __dic_put(Val d, Val key, Val value);
void __dic_remove(Val d, Val key);
void __dic_set(char *pos, Val d, Val key, Val value);
Val __dic_size(Val d);
Val __dic_toArr (Val d);
Val __dic_toIter (Val d);
Val __dic_toJs (Val d, Val fn);
Map *__dic_to_smap (Val a);
Val __dic_values (Val d);

Val __file_aopen (Val path);
Val __file_base (Val path);
Val __file_canonical (char *pos, Val path);
Val __file_cat (Val path, Val rpaths);
void __file_cd (Val path);
Val __file_clean (Val path);
void __file_close (Val file);
void __file_copy (char *pos, Val source, Val target);
void __file_del (Val path);
Val __file_dir (Val path);
Val __file_exists (Val path);
Val __file_extension (Val path);
Val __file_isDirectory (Val path);
Val __file_isLink (Val path);
Val __file_isRegular (Val path);
void __file_mkdir (Val path);
void __file_mklink (Val path, Val link);
Val __file_parent (Val path);
Val __file_read (Val path);
Val __file_readBin (Val file, Val buf);
Val __file_readLine (Val file);
void __file_rename (Val old_path, Val new_path);
Val __file_ropen (Val path);
Val __file_size (Val path);
Val __file_tm (Val path);
Val __file_tmp (Val dir, Val name);
Val __file_wd (void);
Val __file_wopen (Val path);
void __file_write (Val path, Val tx);
void __file_writeBin (Val file, Val bs);
void __file_writeText (Val file, Val tx);

Val __iter_all (Val it, Val fn);
Val __iter_any (Val it, Val fn);
Val __iter_cat (Val it1, Val it2);
Val __iter_count (Val it);
Val __iter_drop (Val it, Val n);
Val __iter_dropWhile (Val it, Val fn);
void __iter_each (Val it, Val fn);
void __iter_eachIx (Val it, Val fn);
Val __iter_empty (Val fake);
Val __iter_filter (Val it, Val fn);
Val __iter_find (Val it, Val fn);
Val __iter_fromJs (Val s, Val fn);
Val __iter_hasNext (Val it);
Val __iter_index (Val it, Val fn);
Val __iter_map (Val it, Val fn);
Val __iter_next (Val it);
Val __iter_new (Val tuple);
Val __iter_new_aux (Val obj, Val (*fn) (Val));
Val __iter_peek (Val it);
Val __iter_range (char *pos, Val vs);
Val __iter_reduce (Val it, Val seed, Val fn);
Val __iter_take (Val it, Val n);
Val __iter_takeWhile (Val it, Val fn);
Val __iter_toJs (Val it, Val fn);
Val __iter_unary (Val value);

Val __js_isNull (Val json);
Val __js_ra (Val json);
Val __js_rb (Val json);
Val __js_rf (Val json);
Val __js_ri (Val json);
Val __js_ro (Val json);
Val __js_rs (Val json);
Val __js_wa(Val a);
Val __js_wb(Val value);
Val __js_wf(Val n);
Val __js_wf2(Val n, Val dec);
Val __js_wi(Val n);
Val __js_wn(void);
Val __js_wo(Val m);
Val __js_ws(Val s);

Val __math_abs (Val n);
Val __math_acos (Val n);
Val __math_acosh (Val n);
Val __math_asin (Val n);
Val __math_asinh (Val n);
Val __math_atan (Val n);
Val __math_atanh (Val n);
Val __math_ceil (Val n);
Val __math_cos (Val n);
Val __math_cosh (Val n);
Val __math_e (void);
Val __math_eq (Val n1, Val n2, Val gap);
Val __math_exp (Val n);
Val __math_exp2 (Val n);
Val __math_floor (Val n);
Val __math_fromEn (Val s);
Val __math_fromHex (Val s);
Val __math_fromIso (Val s);
Val __math_ftoi (Val n);
Val __math_ftos (Val n);
Val __math_ftos2 (Val n, Val dec);
Val __math_isDigits (Val n);
Val __math_itof (Val n);
Val __math_itoh (Val n);
Val __math_itos (Val n);
Val __math_log (Val n);
Val __math_log10 (Val n);
Val __math_log2 (Val n);
Val __math_max (Val n1, Val n2);
Val __math_maxFloat (void);
Val __math_maxInt (void);
Val __math_min (Val n1, Val n2);
Val __math_minInt (void);
Val __math_pi (void);
Val __math_pow (Val base, Val exp);
Val __math_pow10 (Val exp);
Val __math_rnd (void);
Val __math_rndi (Val top);
Val __math_round (Val n, Val dec);
Val __math_sin (Val n);
Val __math_sinh (Val n);
Val __math_sqrt (Val n);
Val __math_stof (Val s);
Val __math_stoi (Val s);
Val __math_tan (Val n);
Val __math_tanh (Val n);
Val __math_trunc (Val n);

Val __regex_matches (char *pos, Val s, Val rg);
Val __regex_replace (char *pos, Val s, Val rg, Val repl);
Val __regex_replacef (char *pos, Val s, Val rg, Val frpl);

Val __rs_some (Val v);
Val __rs_ok (Val v);
Val __rs_fail (Val v);
Val __rs_get (Val rs);
Val __rs_error (Val rs);

Val __str_cmp (Val s1, Val s2);
Val __str_ends (Val str, Val substr);
Val __str_fmt (char *pos, Val format, Val args);
Val __str_fromIso (Val s);
Val __str_fromRunes (Val a);
Val __str_fromUtf16 (Val codepoints);
Val __str_get(char *pos, Val s, Val ix);
Val __str_index (Val str, Val substr);
Val __str_indexFrom (Val str, Val substr, Val start);
Val __str_lastIndex (Val str, Val substr);
Val __str_left (Val str, Val end);
Val __str_left_slice(Val str, Val begin);
Val __str_len (Val str);
Val __str_ltrim (Val str);
Val __str_replace (Val s, Val old, Val new);
Val __str_right (Val str, Val end);
Val __str_right_slice(Val str, Val begin);
Val __str_rtrim (Val str);
Val __str_split (Val str, Val sep);
Val __str_splitTrim (Val str, Val sep);
Val __str_starts (Val str, Val substr);
Val __str_sub(Val str, Val begin, Val end);
Val __str_sub_slice(Val str, Val begin, Val end);
Val __str_toLower (Val str);
Val __str_toRunes (Val str);
Val __str_toUpper (Val str);
Val __str_toUtf16 (Val str);
Val __str_trim (Val str);

void __sys_init(int argc, char **argv, char *compiler_root);
Val __sys_args (void);
Val __sys_cmd (Val command, Val args);
Val __sys_cmd2 (Val command, Val args);
Val __sys_compilerRoot (void);
Val __sys_environ (void);
void __sys_exit (Val code);
Val __sys_getLocale (void);
Val __sys_home (void);
Val __sys_mainPath (void);
Val __sys_pid (void);
void __sys_printError (Val text);
Val __sys_readLine (void);
void __sys_setLocale (Val charset);
void __sys_sleep (Val millis);
Val __sys_user (void);

Val __tcp_accept (Val server);
void __tcp_closeConnection (Val conn);
void __tcp_closeServer (Val server);
Val __tcp_dial (Val server_name);
Val __tcp_read (Val conn, Val lim, Val seconds);
Val __tcp_server (Val port, Val nconns);
Val __tcp_write (Val conn, Val data);

void __thread_join (Val th);
void __thread_run (Val fn);
Val __thread_start (Val fn);
void __thread_sync (Val fn);

Val __time_addDays (Val tm, Val days);
Val __time_day (Val tm);
Val __time_dfDays (Val tm1, Val tm2);
Val __time_eqDay (Val tm1, Val tm2);
Val __time_fmt (Val tm, Val template);
Val __time_fromClock (Val tm, Val template);
Val __time_fromEn (Val s, Val sep);
Val __time_fromIso (Val s, Val sep);
Val __time_fromStr (Val s);
Val __time_hour (Val tm);
Val __time_millisecond (Val tm);
Val __time_minute (Val tm);
Val __time_month (Val tm);
Val __time_new (Val day, Val month, Val year, Val hour, Val minute, Val second);
Val __time_newDate (Val day, Val month, Val year);
Val __time_now (void);
Val __time_second (Val tm);
Val __time_toEn (Val tm);
Val __time_toIso (Val tm);
Val __time_toStr (Val tm);
Val __time_weekday (Val tm);
Val __time_year (Val tm);
Val __time_yearDay (Val tm);

