// Copyright 21-Jun-2025 ºDeme
// GNU General Public License - V3 <http://www.gnu.org/licenses/>

char *cryp_bget (void) {return
  "// Copyright 17-Apr-2023 ºDeme\n"
  "// GNU General Public License - V3 <http://www.gnu.org/licenses/>\n"
  "\n"
  "import * as sys from './sys.js';\n"
  "import * as b64 from './b64.js';\n"
  "\n"
  "// \\n -> s\n"
  "export function genK (lg) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  const bs = new Uint8Array(lg);\n"
  "  for (let i = 0; i < lg; ++i) bs[i] = Math.floor(Math.random() * 256);\n"
  "  return b64.encodeBytes(bs).substring(0, lg);\n"
  "}\n"
  "\n"
  "// \\s, n -> s\n"
  "export function key (key, lg) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "    const k = b64.decodeBytes(b64.encode(\n"
  "      key + \"codified in irreversibleDeme is good, very good!\\n\\r8@@\"\n"
  "    ));\n"
  "    const lenk = k.length;\n"
  "    let sum = 0;\n"
  "    for (let i = 0; i < lenk; ++i) sum += k[i];\n"
  "\n"
  "    const lg2 = lg + lenk;\n"
  "    const r = new Uint8Array(lg2);\n"
  "    const r1 = new Uint8Array(lg2);\n"
  "    const r2 = new Uint8Array(lg2);\n"
  "    let ik = 0;\n"
  "    for (let i = 0; i < lg2; ++i) {\n"
  "      const v1 = k[ik];\n"
  "      const v2 = v1 + k[v1 % lenk];\n"
  "      const v3 = v2 + k[v2 % lenk];\n"
  "      const v4 = v3 + k[v3 % lenk];\n"
  "      sum = sum + i + v4;\n"
  "      r1[i] = sum;\n"
  "      r2[i] = sum;\n"
  "      ++ik;\n"
  "      if (ik == lenk) ik = 0;\n"
  "    }\n"
  "\n"
  "    for (let i = 0; i < lg2; ++i) {\n"
  "      const v1 = r2[i];\n"
  "      const v2 = v1 + r2[v1 % lg2];\n"
  "      const v3 = v2 + r2[v2 % lg2];\n"
  "      const v4 = v3 + r2[v3 % lg2];\n"
  "      sum = sum + v4;\n"
  "      r2[i] = sum;\n"
  "      r[i] = sum + r1[i];\n"
  "    }\n"
  "\n"
  "    return b64.encodeBytes(r).substring(0, lg);\n"
  "  }\n"
  "\n"
  "// \\s, s -> s\n"
  "export function encode (k, msg) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  const m = b64.encode(msg);\n"
  "  const lg = m.length;\n"
  "  const k2 = key(k, lg);\n"
  "  const r = new Uint8Array(lg);\n"
  "  for (let i = 0; i < lg; ++i) r[i] = m.charCodeAt(i) + k2.charCodeAt(i);\n"
  "\n"
  "  return b64.encodeBytes(r);\n"
  "}\n"
  "\n"
  "// \\s, s -> s\n"
  "export function decode (k, b64Tx) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  const bs = b64.decodeBytes(b64Tx);\n"
  "  const lg = bs.length;\n"
  "  const k2 = key(k, lg);\n"
  "  const r = [];\n"
  "  for (let i = 0; i < lg; ++i)\n"
  "    r.push(String.fromCharCode(bs[i] - k2.charCodeAt(i)));\n"
  "\n"
  "  return b64.decode(r.join(\"\"));\n"
  "}\n"
  "\n"
;}
