// Copyright 21-Jun-2025 ºDeme
// GNU General Public License - V3 <http://www.gnu.org/licenses/>

char *dic_bget (void) {return
  "// Copyright 01-May-2023 ºDeme\n"
  "// GNU General Public License - V3 <http://www.gnu.org/licenses/>\n"
  "\n"
  "import * as sys from './sys.js';\n"
  "import * as arr from './arr.js';\n"
  "import * as iter from './iter.js';\n"
  "\n"
  "// \\d -> d\n"
  "export function copy (d) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  const r = {};\n"
  "  for (const k in d) r[k] = d[k];\n"
  "  return r;\n"
  "}\n"
  "\n"
  "// \\[[s,*]...] -> d\n"
  "export function fromArr (a) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  const r = {};\n"
  "  for (const kv of a) r[kv[0]] = kv[1];\n"
  "  return r;\n"
  "}\n"
  "\n"
  "// \\<iter>[[s,*]...] -> d\n"
  "export function fromIter (it) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  const r = {};\n"
  "  while (iter.hasNext(it)) {\n"
  "    const kv = iter.next(it);\n"
  "    r[kv[0]] = kv[1];\n"
  "  }\n"
  "  return r;\n"
  "}\n"
  "\n"
  "// \\d, s -> []|[*]\n"
  "export function get (d, k) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  return sys.$null(d[k]);\n"
  "}\n"
  "\n"
  "// \\d, s -> b\n"
  "export function hasKey (d, k) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  return d.propertyIsEnumerable(k);\n"
  "}\n"
  "\n"
  "// \\d -> [s...]\n"
  "export function keys (d) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return Object.keys(d);\n"
  "}\n"
  "\n"
  "// \\d, s, * -> ()\n"
  "export function put (d, k, v) {\n"
  "  sys.$params(arguments.length, 3);\n"
  "  return d[k] = v;\n"
  "}\n"
  "\n"
  "// \\d, s -> ()\n"
  "export function remove (d, k) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  delete d[k];\n"
  "}\n"
  "\n"
  "// \\d -> n\n"
  "export function size (d) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return Object.keys(d).length;\n"
  "}\n"
  "\n"
  "// \\d -> [[s,*]...]\n"
  "export function toArr (d) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  const r = [];\n"
  "  const keys = Object.keys(d);\n"
  "  r.length = keys.length;\n"
  "  for (let i = 0; i < keys.length; ++i) {\n"
  "    const k = keys[i];\n"
  "    r[i] = [k, d[k]];\n"
  "   }\n"
  "  return r;\n"
  "}\n"
  "\n"
  "// \\d -> <iter>[[s,*]...]\n"
  "export function toIter (d) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  const keys = Object.keys(d);\n"
  "  let ix = 0;\n"
  "  return iter.mk(\n"
  "    () => ix < keys.length,\n"
  "    () => {\n"
  "        const k = keys[ix++];\n"
  "        return [k, d[k]];\n"
  "      }\n"
  "  );\n"
  "}\n"
  "\n"
  "// \\d -> a\n"
  "export function values (d) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  const r = [];\n"
  "  const keys = Object.keys(d);\n"
  "  r.length = keys.length;\n"
  "  for (let i = 0; i < keys.length; ++i) r[i] = d[keys[i]];\n"
  "  return r;\n"
  "}\n"
  "\n"
  "\n"
;}
