// Copyright 23-Nov-2024 ºDeme
// GNU General Public License - V3 <http://www.gnu.org/licenses/>

char *str_bget (void) {return
  "// Copyright 16-Apr-2023 ºDeme\n"
  "// GNU General Public License - V3 <http://www.gnu.org/licenses/>\n"
  "\n"
  "import * as sys from './sys.js';\n"
  "\n"
  "// \\s, s -> b\n"
  "export function great (s1, s2) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  return s1.localeCompare(s2) > 0;\n"
  "}\n"
  "\n"
  "// \\s, s -> b\n"
  "export function ends (s, sub) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  return s.endsWith(sub);\n"
  "}\n"
  "\n"
  "// \\s -> s\n"
  "export function escape (s) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  const raw = /[\\w*+\\-./@]/;\n"
  "  let r = [];\n"
  "  let i = 0;\n"
  "  while (i < s.length) {\n"
  "    const ch = s.charAt(i++);\n"
  "    if (raw.test(ch.charAt(0))) r.push(ch);\n"
  "    else {\n"
  "      const hex = ch.codePointAt(0).toString(16);\n"
  "      switch (hex.length) {\n"
  "        case 1:\n"
  "        case 3:\n"
  "          r.push('%0' + hex);\n"
  "          break;\n"
  "        default:\n"
  "          r.push('%' + hex);\n"
  "      }\n"
  "    }\n"
  "  }\n"
  "  return r.join('');\n"
  "}\n"
  "\n"
  "// \\s, a -> s\n"
  "export function fmt (t, sb) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  if (t.length === 0) throw new Error(\"Template is empty\");\n"
  "\n"
  "  let ix = 0;\n"
  "  let p = 0;\n"
  "  let r = [];\n"
  "  while (true) {\n"
  "    const p2 = t.indexOf(\"%\", p);\n"
  "    if (p2 === -1) break;\n"
  "\n"
  "    r.push(t.substring(p, p2));\n"
  "    p = p2 + 1;\n"
  "\n"
  "    if (p === t.length) throw new Error(\"Template ends at '%'\");\n"
  "    const ch = t.charAt(p);\n"
  "    if (ch === \"%\") {\n"
  "      r.push(\"%\");\n"
  "      ++p;\n"
  "    } else if (ch === \"v\") {\n"
  "      if (ix >= sb.length)\n"
  "        throw new Error(\"Missing values replacing '\" + t + \"'\");\n"
  "      r.push(sys.toStr(sb[ix++]));\n"
  "      ++p;\n"
  "    } else {\n"
  "      throw new Error(\"Character after '%' (\" + ch + \") is not '%' nor 'v'\");\n"
  "    }\n"
  "  }\n"
  "  if (ix !== sb.length) throw new Error(\"Extra values replacing '\" + t + \"'\");\n"
  "\n"
  "  r.push(t.substring(p));\n"
  "  return r.join(\"\");\n"
  "}\n"
  "\n"
  "// \\[n...] -> s\n"
  "export function fromCodePoints (cps) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return String.fromCodePoint(...cps);\n"
  "}\n"
  "\n"
  "// \\s -> s\n"
  "export function fromUtf8 (s) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return decodeURIComponent(escape(s));\n"
  "}\n"
  "\n"
  "// \\s, s -> n\n"
  "export function index (s, sub) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  return s.indexOf(sub);\n"
  "}\n"
  "\n"
  "// \\s, s, n -> n\n"
  "export function indexFrom (s, sub, ix) {\n"
  "  sys.$params(arguments.length, 3);\n"
  "  return s.indexOf(sub, ix);\n"
  "}\n"
  "\n"
  "// \\s, s -> n\n"
  "export function lastIndex (s, sub) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  return s.lastIndexOf(sub);\n"
  "}\n"
  "\n"
  "// \\s -> n\n"
  "export function len (s) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return s.length;\n"
  "}\n"
  "\n"
  "// \\s, s -> b\n"
  "export function less (s1, s2) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  return s1.localeCompare(s2) < 0;\n"
  "}\n"
  "\n"
  "// \\s -> s\n"
  "export function ltrim (s) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return s.trimStart();\n"
  "}\n"
  "\n"
  "// \\s, s, s -> s\n"
  "export function replace (s, olds, news) {\n"
  "  sys.$params(arguments.length, 3);\n"
  "  return s.replaceAll(olds, news);\n"
  "}\n"
  "\n"
  "// \\s -> s\n"
  "export function rtrim (s) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return s.trimEnd();\n"
  "}\n"
  "\n"
  "// \\s, s -> [s...]\n"
  "export function split (s, sep) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  return s.split(sep);\n"
  "}\n"
  "\n"
  "// \\s, s -> [s...]\n"
  "export function splitTrim (s, sep) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  return s.split(sep).map(e => e.trim());\n"
  "}\n"
  "\n"
  "// \\s, s -> b\n"
  "export function starts (s, sub) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  return s.startsWith(sub);\n"
  "}\n"
  "\n"
  "// \\s -> [n...]\n"
  "export function toCodePoints (s) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  const r = [];\n"
  "  r.length = s.length;\n"
  "  for (let i = 0; i < s.length; ++i) r[i] = s.codePointAt(i);\n"
  "  return r;\n"
  "}\n"
  "\n"
  "// \\s -> s\n"
  "export function toLower(s) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return s.toLowerCase();\n"
  "}\n"
  "\n"
  "// \\s -> s\n"
  "export function toUpper (s) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return s.toUpperCase();\n"
  "}\n"
  "\n"
  "// \\s -> s\n"
  "export function toUtf8 (s) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return unescape(encodeURIComponent(s));\n"
  "}\n"
  "\n"
  "// \\s -> s\n"
  "export function trim (s) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return s.trim();\n"
  "}\n"
  "\n"
  "// \\s -> s\n"
  "export function unescape (s) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return s.replace(\n"
  "    /%([0-9A-Fa-f]{2})/g, (match, p1) => String.fromCharCode('0x' + p1)\n"
  "  );\n"
  "}\n"
  "\n"
  "\n"
;}
