// Copyright 23-Nov-2024 ºDeme
// GNU General Public License - V3 <http://www.gnu.org/licenses/>

char *sys_bget (void) {return
  "// Copyright 16-Apr-2023 ºDeme\n"
  "// GNU General Public License - V3 <http://www.gnu.org/licenses/>\n"
  "\n"
  "import { argv, env, pid as ppid, exit as pexit, stdout } from \"process\";\n"
  "import {execFileSync} from \"child_process\";\n"
  "\n"
  "export function $slice (o, begin, end) {\n"
  "  if (typeof(o) === 'string') {\n"
  "    const len = o.length;\n"
  "    begin = begin === null ? 0 : begin < 0 ? len + begin : begin;\n"
  "    begin = begin < 0 ? 0 : begin > len ? len : begin;\n"
  "\n"
  "    end = end === null ? len : end < 0 ? len + end : end;\n"
  "    end = end < begin ? begin : end > len ? len : end;\n"
  "    return o.substring(begin, end);\n"
  "  }\n"
  "  if (Array.isArray(o)) {\n"
  "    if (begin === null) begin = 0;\n"
  "    if (end === null) end = o.length;\n"
  "    return o.slice(begin, end);\n"
  "  }\n"
  "\n"
  "  throw new Error('\\nExpected: Array or string.\\n   Found: ' + o);\n"
  "}\n"
  "\n"
  "export function $eq (e1, e2) {\n"
  "  if (typeof(e1) !== typeof(e2)) return false;\n"
  "  if (typeof(e1) === 'object') {\n"
  "    if (Array.isArray(e1)) {\n"
  "      if (Array.isArray(e2)) {\n"
  "        if (e1.length !== e2.length) return false;\n"
  "        for (let i = 0; i < e1.length; i++)\n"
  "          if (!$eq(e1[i], e2[i])) return false;\n"
  "        return true;\n"
  "      }\n"
  "      return false;\n"
  "    }\n"
  "    if (Array.isArray(e2)) return false;\n"
  "    if (Object.prototype.toString.call(e1) === '[object Object]') {\n"
  "      if (Object.prototype.toString.call(e2) === '[object Object]') {\n"
  "        const keys1 = Object.keys(e1);\n"
  "        const keys2 = Object.keys(e2);\n"
  "        if (keys1.length !== keys2.length) return false;\n"
  "        for (let i = 0; i < keys1.length; i++) {\n"
  "          const k = keys1[i];\n"
  "          if (!$eq(e1[k], e2[k])) return false;\n"
  "        }\n"
  "        return true;\n"
  "      }\n"
  "      return false;\n"
  "    }\n"
  "    if (Object.prototype.toString.call(e2) === '[object Object]') return false;\n"
  "  }\n"
  "  if (typeof(e1) === 'number' || typeof(e2) === 'number')\n"
  "    return e1 + 0.0000001 >= e2 && e1 - 0.0000001 <= e2;\n"
  "  return e1 === e2;\n"
  "}\n"
  "\n"
  "export function $neq (e1, e2) {\n"
  "  return !$eq(e1, e2);\n"
  "}\n"
  "\n"
  "export function $forObject (o) {\n"
  "  if (Object.prototype.toString.call(o) === '[object Object]')\n"
  "    return Object.values(o);\n"
  "  return o;\n"
  "}\n"
  "\n"
  "export function $forObject2 (o) {\n"
  "  if (Object.prototype.toString.call(o) === '[object Object]')\n"
  "    return Object.entries(o);\n"
  "  return o.entries();\n"
  "}\n"
  "\n"
  "export function $forCmp (v) {\n"
  "  if (v === 0) throw new Error('Step of for loop is 0');\n"
  "  if (v > 0) return (v, l) => (v <= l);\n"
  "  return (v, l) => (v >= l);\n"
  "}\n"
  "\n"
  "export function $params (actual, expected) {\n"
  "  if (actual != expected)\n"
  "    throw new Error(\n"
  "      'Bad number of parameters' +\n"
  "      '\\n  Expected: ' + expected +\n"
  "      '\\n    Actual: ' + actual\n"
  "    );\n"
  "}\n"
  "\n"
  "export function $fparams (fn, expected) {\n"
  "  const actual = fn.length;\n"
  "  if (actual != expected)\n"
  "    throw new Error(\n"
  "      'Bad number of parameters in ' + fn +\n"
  "      '\\n  Expected: ' + expected +\n"
  "      '\\n    Actual: ' + actual\n"
  "    );\n"
  "}\n"
  "\n"
  "export function $null (v) {\n"
  "  if (v == null) return [];\n"
  "  return [v];\n"
  "}\n"
  "\n"
  "export function $checkExists (left, right) {\n"
  "  if (left == null) throw new Error('Index out of range or key not found');\n"
  "  return right;\n"
  "}\n"
  "\n"
  "export function $checkNull (v) {\n"
  "  if (typeof(v) === \"number\" && !Number.isFinite(v))\n"
  "    throw new Error ('Bad Number ' + v);\n"
  "  if (v == null) throw new Error('Null expression ' + v);\n"
  "  return v;\n"
  "}\n"
  "\n"
  "export function $trace (v) {\n"
  "  $params(arguments.length, 1);\n"
  "  const er = new Error(toStr(v));\n"
  "  let msg = er.stack.split(\"\\n\")[2];\n"
  "  msg = msg.substring(msg.indexOf(\"/\") + 2, msg.lastIndexOf(\":\"));\n"
  "  console.log(msg + \": \" + er.message);\n"
  "}\n"
  "\n"
  "// Built-in --------------------\n"
  "\n"
  "// \\* -> [s.]\n"
  "export function args () {\n"
  "  $params(arguments.length, 0);\n"
  "  return argv;\n"
  "}\n"
  "\n"
  "\n"
  "// \\* -> b\n"
  "export function asBool (e) {\n"
  "  $params(arguments.length, 1);\n"
  "  if (typeof(e) === 'boolean') return e;\n"
  "  if (Array.isArray(e)) return e.length != 0;\n"
  "  throw new Error('\\nExpected: boolean or Array.\\n   Found: ' + e);\n"
  "}\n"
  "\n"
  "// \\* -> ()\n"
  "export function assert (v) {\n"
  "  $params(arguments.length, 1);\n"
  "  if (!v)\n"
  "    throw new Error('Assert failed');\n"
  "}\n"
  "\n"
  "// \\s, [s.] -> [s, b](Result)\n"
  "export function cmd (c, pars) {\n"
  "  $params(arguments.length, 2);\n"
  "  const [ out, err ] = cmd2(c, pars);\n"
  "  return out === \"\" ? [err, false] : [out, true];\n"
  "}\n"
  "\n"
  "// \\s, [s.] -> [s, s]\n"
  "export function cmd2 (c, pars) {\n"
  "  $params(arguments.length, 2);\n"
  "\n"
  "  try {\n"
  "    const stdout = execFileSync(c, pars, {\n"
  "      stdio: 'pipe',\n"
  "      encoding: 'utf8',\n"
  "    });\n"
  "\n"
  "    return [stdout, \"\"];\n"
  "  } catch (err) {\n"
  "    if (err.code)\n"
  "      return [\"\", \"NOEXEC: \" + err.message];\n"
  "    else {\n"
  "      return [\"\", err.message];\n"
  "    }\n"
  "  }\n"
  "}\n"
  "\n"
  "// \\ -> {s.}\n"
  "export function environ () {\n"
  "  $params(arguments.length, 0);\n"
  "  return env;\n"
  "}\n"
  "\n"
  "// \\ -> s\n"
  "export function getLocale () {\n"
  "  $params(arguments.length, 0);\n"
  "  return env[\"LANG\"];\n"
  "}\n"
  "\n"
  "// \\n -> ()\n"
  "export function exit (n) {\n"
  "  $params(arguments.length, 1);\n"
  "  return pexit(n);\n"
  "}\n"
  "\n"
  "// \\ -> s\n"
  "export function home () {\n"
  "  $params(arguments.length, 0);\n"
  "  return env[\"HOME\"];\n"
  "}\n"
  "\n"
  "// \\ -> s\n"
  "export function pid () {\n"
  "  $params(arguments.length, 0);\n"
  "  return ppid;\n"
  "}\n"
  "\n"
  "// \\ -> s\n"
  "export function mainPath () {\n"
  "  $params(arguments.length, 0);\n"
  "  return argv[1];\n"
  "}\n"
  "\n"
  "// \\* -> ()\n"
  "export function print (v) {\n"
  "  $params(arguments.length, 1);\n"
  "  stdout.write(toStr(v));\n"
  "}\n"
  "\n"
  "// \\* -> ()\n"
  "export function printError (v) {\n"
  "  $params(arguments.length, 1);\n"
  "  console.error(toStr(v));\n"
  "}\n"
  "\n"
  "// \\* -> ()\n"
  "export function println (v) {\n"
  "  $params(arguments.length, 1);\n"
  "  console.log(toStr(v));\n"
  "}\n"
  "\n"
  "// \\s -> ()\n"
  "export function raise (v) {\n"
  "  $params(arguments.length, 1);\n"
  "  throw new Error(v);\n"
  "}\n"
  "\n"
  "// \\*, * -> ()\n"
  "export function test (actual, expected) {\n"
  "  $params(arguments.length, 2);\n"
  "  if ($neq(actual, expected))\n"
  "    throw new Error(\n"
  "      'Test failed:\\nExpected: ' + JSON.stringify(expected) +\n"
  "      '\\n  Actual: ' + JSON.stringify(actual)\n"
  "    );\n"
  "}\n"
  "\n"
  "// \\* -> s\n"
  "export function toStr (v) {\n"
  "  $params(arguments.length, 1);\n"
  "  if (v == null) return \"<null>\";\n"
  "  if (type(v) === \"[object Object]\") return JSON.stringify(v);\n"
  "  return v.toString();\n"
  "}\n"
  "\n"
  "// \\* -> s\n"
  "export function type (v) {\n"
  "  $params(arguments.length, 1);\n"
  "  if (typeof(v) === 'object')\n"
  "    return Object.prototype.toString.call(v);\n"
  "  return typeof(v);\n"
  "}\n"
  "\n"
  "// \\ -> s\n"
  "export function user () {\n"
  "  $params(arguments.length, 0);\n"
  "  return env[\"USER\"];\n"
  "}\n"
  "\n"
  "\n"
;}
