// Copyright 06-Sep-2024 ºDeme
// GNU General Public License - V3 <http://www.gnu.org/licenses/>

char *timer_bget (void) {return
  "// Copyright 03-May-2023 ºDeme\n"
  "// GNU General Public License - V3 <http://www.gnu.org/licenses/>\n"
  "\n"
  "import * as sys from './sys.js';\n"
  "\n"
  "// \\i, (\\->*) -> <promise>*\n"
  "export function delay (tm, fn) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  sys.$fparams(fn, 0);\n"
  "  return new Promise((resolve) => {\n"
  "    setTimeout(() => {\n"
  "      resolve(fn());\n"
  "    }, tm);\n"
  "  });\n"
  "}\n"
  "\n"
  "// \\i -> <timer>\n"
  "export function mk (tm) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return [true, tm];\n"
  "}\n"
  "\n"
  "// \\<timer>, (\\->*) -> <promise>*\n"
  "export async function run (t, fn) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  sys.$fparams(fn, 0);\n"
  "  if (!t[0]) throw new Error('Timer has been stopped');\n"
  "\n"
  "  async function loop () {\n"
  "    const r = await delay(t[1], fn);\n"
  "    if (t[0]) return loop();\n"
  "    else return r;\n"
  "  }\n"
  "\n"
  "  return await loop();\n"
  "}\n"
  "\n"
  "// \\<timer> -> ()\n"
  "export function stop (t) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  if (!t[0]) throw new Error('Timer is not running');\n"
  "  t[0] = false;\n"
  "}\n"
  "\n"
;}
