// Copyright 19-Jun-2024 ºDeme
// GNU General Public License - V3 <http://www.gnu.org/licenses/>

char *ui_bget (void) {return
  "// Copyright 03-May-2023 ºDeme\n"
  "// GNU General Public License - V3 <http://www.gnu.org/licenses/>\n"
  "\n"
  "import * as sys from './sys.js';\n"
  "import * as iter from './iter.js';\n"
  "import * as arr from './arr.js';\n"
  "import * as timer from './timer.js';\n"
  "import * as domo from './domo.js';\n"
  "\n"
  "// \\s -> ()\n"
  "export function alert (s) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  window.alert(s);\n"
  "}\n"
  "\n"
  "// \\-> ()\n"
  "export function beep () {\n"
  "  sys.$params(arguments.length, 0);\n"
  "  const au = new AudioContext();\n"
  "  const o = au.createOscillator();\n"
  "  o.frequency.value = 990;\n"
  "  o.connect(au.destination);\n"
  "  o.start(0);\n"
  "  timer.delay(120, () => o.stop(0));\n"
  "}\n"
  "\n"
  "// \\<domo> -> <domo>\n"
  "export function changePoint (inp) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  const el = inp.e;\n"
  "  const ac = el.onkeydown;\n"
  "  el.onkeydown = function (e) {\n"
  "    if (e.keyCode === 110) {\n"
  "      const start = el.selectionStart;\n"
  "      const end = el.selectionEnd;\n"
  "      const text = el.value;\n"
  "\n"
  "      el.value = text.substring(0, start) + \",\" + text.substring(end);\n"
  "      el.selectionStart = start + 1;\n"
  "      el.selectionEnd = start + 1;\n"
  "\n"
  "      return false;\n"
  "    }\n"
  "\n"
  "    if (ac !== null) ac(e);\n"
  "    return true;\n"
  "  }\n"
  "  return inp;\n"
  "}\n"
  "\n"
  "// \\s -> b\n"
  "export function confirm (s) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return window.confirm(s);\n"
  "}\n"
  "\n"
  "// \\s -> <domo>\n"
  "export function field (targetId) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  const r = q(\"input\").att(\"type\", \"text\");\n"
  "  r.e.onkeydown = function (e) {\n"
  "    if (e.keyCode === 13) {\n"
  "      e.preventDefault();\n"
  "      q(\"#\" + targetId).e.focus();\n"
  "    }\n"
  "  }\n"
  "  return r;\n"
  "}\n"
  "\n"
  "// \\s, i -> <domo>\n"
  "export function hrule (label, margin) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  return q(\"table\")\n"
  "    .style(\n"
  "      \"border-collapse: collapse;\" +\n"
  "      \"border : 0px;\" +\n"
  "      \"width : 100%\")\n"
  "    .add(q(\"tr\")\n"
  "      .add(q(\"td\")\n"
  "        .style(\"width: \" + margin + \"px\")\n"
  "        .add(q(\"hr\")))\n"
  "      .add(q(\"td\")\n"
  "        .style(\"white-space:nowrap; width: 5px\")\n"
  "        .text(\" \" + label + \" \"))\n"
  "      .add(q(\"td\")\n"
  "        .add(q(\"hr\"))))\n"
  "  ;\n"
  "}\n"
  "\n"
  "// \\<domo>, (\\<fileList>->()) -> ()\n"
  "export function ifiles (o, fn) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  sys.$fparams(fn, 1);\n"
  "  const style = o.getAtt(\"style\");\n"
  "  function handleDragOver (evt) {\n"
  "    o.att(\"style\", style + \";background-color: rgb(240, 245, 250);\");\n"
  "    evt.stopPropagation();\n"
  "    evt.preventDefault();\n"
  "    evt.dataTransfer.dropEffect = 'copy';\n"
  "  }\n"
  "  o.e.addEventListener(\"dragover\", handleDragOver, false);\n"
  "\n"
  "  o.e.addEventListener(\"dragleave\", function (evt) {\n"
  "    o.att(\"style\", style);\n"
  "  }, false);\n"
  "\n"
  "  function handleDrop (evt) {\n"
  "    o.att(\"style\", style);\n"
  "    evt.stopPropagation();\n"
  "    evt.preventDefault();\n"
  "\n"
  "    fn(evt.dataTransfer.files);\n"
  "  }\n"
  "  o.e.addEventListener(\"drop\", handleDrop, false);\n"
  "\n"
  "  return o;\n"
  "}\n"
  "\n"
  "// \\s -> <domo>\n"
  "export function img (name) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  if (name.indexOf(\".\") === -1) name = name + \".png\";\n"
  "  return q(\"img\").att(\"src\", \"img/\" + name);\n"
  "}\n"
  "\n"
  "// \\s, i -> <domo>\n"
  "export function led (color, side) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  return q(\"div\")\n"
  "    .style(\n"
  "      \"padding:\" + side + \"px;\" +\n"
  "       \"border: 1px solid #002040;border-radius: \" + side + \"px;\" +\n"
  "       \"background: \" + color + \";\"\n"
  "    );\n"
  "}\n"
  "\n"
  "// \\s -> <domo>\n"
  "export function lightImg (name) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return img(name).att(\"style\", \"opacity:0.4\");\n"
  "}\n"
  "\n"
  "// \\(\\<event>->()) -> <domo>\n"
  "export function link (fn) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return q(\"span\").att(\"style\", \"cursor:pointer\").on(\"click\", fn);\n"
  "}\n"
  "\n"
  "// \\<event> -> n\n"
  "export function mouseX (ev) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return document.documentElement.scrollLeft +\n"
  "    document.body.scrollLeft +\n"
  "    ev.clientX\n"
  "  ;\n"
  "}\n"
  "\n"
  "// \\<event> -> n\n"
  "export function mouseY (ev) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return document.documentElement.scrollTop +\n"
  "    document.body.scrollTop +\n"
  "    ev.clientY\n"
  "  ;\n"
  "}\n"
  "\n"
  "// \\s -> <domo>\n"
  "export function pass (targetId) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  const r = q(\"input\").att(\"type\", \"password\");\n"
  "  r.e.onkeydown = function (e) {\n"
  "    if (e.keyCode === 13) {\n"
  "      e.preventDefault();\n"
  "      q(\"#\" + targetId).e.focus();\n"
  "    }\n"
  "  }\n"
  "  return r;\n"
  "}\n"
  "\n"
  "// \\\\s, s -> s\n"
  "export function prompt (msg, def) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  if (def === \"\") return prompt(msg);\n"
  "  else return prompt(msg, def);\n"
  "}\n"
  "\n"
  "// \\* -> <domo>\n"
  "export function q (el) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  if (typeof(el) !== \"string\") return domo.mk(el);\n"
  "  switch (el.charAt(0)) {\n"
  "    case \"#\":\n"
  "      return domo.mk(sys.$checkNull(document.getElementById(el.substring(1))));\n"
  "    case \"@\":\n"
  "      return domo.mk(sys.$checkNull(document.querySelector(el.substring(1))));\n"
  "    default:\n"
  "      return domo.mk(sys.$checkNull(document.createElement(el)));\n"
  "  }\n"
  "}\n"
  "\n"
  "// \\* -> [<domo>] | []\n"
  "export function qOp (el) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  if (typeof(el) !== \"string\") return domo.mk(el);\n"
  "  let e = null;\n"
  "  switch (el.charAt(0)) {\n"
  "    case \"#\":\n"
  "      e = document.getElementById(el.substring(1));\n"
  "      return e == null ? [] : [domo.mk(e)];\n"
  "    case \"@\":\n"
  "      e = document.querySelector(el.substring(1));\n"
  "      return e == null ? [] : [domo.mk(e)];\n"
  "    default:\n"
  "      e = document.createElement(el);\n"
  "      return e == null ? [] : [domo.mk(e)];\n"
  "  }\n"
  "}\n"
  "\n"
  "/// \\s -> <iter>[<domo>.]\n"
  "export function qq (s) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  function toIt (lst) {\n"
  "    let c = 0;\n"
  "    const len = lst.length;\n"
  "    return iter.mk(\n"
  "      () => c < len,\n"
  "      () => lst.item(c++)\n"
  "    );\n"
  "  }\n"
  "  if (s === \"\") return toIt(document.getElementsByTagName(\"*\"));\n"
  "  switch (s.charAt(0)) {\n"
  "    case \"%\": return toIt(document.getElementsByName(str.substring(1)));\n"
  "    case \".\": return toIt(document.getElementsByClassName(s.substring(1)));\n"
  "    default: return toIt(document.getElementsByTagName(s));\n"
  "  }\n"
  "}\n"
  "\n"
  "/// \\s, [s...] -> <domo>\n"
  "export function select (idPrefix, list) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  const r = q(\"select\").att(\"id\", idPrefix);\n"
  "  arr.each(list, function (tx) {\n"
  "    const op = q(\"option\");\n"
  "    if (tx.length > 0 && tx.charAt(0) === \"+\") {\n"
  "      tx = tx.substring(1);\n"
  "      op.att(\"selected\", \"true\");\n"
  "    }\n"
  "    op.text(tx).att(\"name\", idPrefix).att(\"id\", idPrefix + \"_\" + tx);\n"
  "    r.e.add(op.e);\n"
  "  });\n"
  "  return r;\n"
  "}\n"
  "\n"
  "/// \\s -> <promise>s\n"
  "export function upload (fpath) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  const url = fpath.charAt(0) === \"/\"\n"
  "    ? \"http://\" + location.host + fpath\n"
  "    : fpath\n"
  "  ;\n"
  "  return new Promise(function (resolve, reject) {\n"
  "    const request = new XMLHttpRequest();\n"
  "    request.open(\"GET\", url, true);\n"
  "    request.onload = () => {\n"
  "      if (request.status >= 200 && request.status < 300)\n"
  "        resolve(request.responseText);\n"
  "      else reject(new Error(request.statusText));\n"
  "    };\n"
  "    request.onerror = () => reject(new Error(request.statusText));\n"
  "    request.onabort = () => reject(new Error(request.statusText));\n"
  "\n"
  "    request.send();\n"
  "  });\n"
  "}\n"
  "\n"
  "// \\s -> <domo>\n"
  "export function upTop (image) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return q(\"div\")\n"
  "    .style(\"position: fixed;bottom: 0px;right: 20px\")\n"
  "    .add(link(() => scroll(0, 0))\n"
  "      .add(img(image)))\n"
  "  ;\n"
  "}\n"
  "\n"
  "// \\-> [s...]\n"
  "export function url () {\n"
  "  sys.$params(arguments.length, 0);\n"
  "  const search = location.search;\n"
  "  if (search === \"\") return [];\n"
  "  return arr.map(search.substring(1).split(\"&\"), decodeURI);\n"
  "}\n"
  "\n"
;}
