// Copyright 08-May-2023 ºDeme
// GNU General Public License - V3 <http://www.gnu.org/licenses/>

char *b64_bget (void) {return
  "// Copyright 17-Apr-2023 ºDeme\n"
  "// GNU General Public License - V3 <http://www.gnu.org/licenses/>\n"
  "\n"
  "import * as sys from './sys.js';\n"
  "import * as str from './str.js';\n"
  "\n"
  "// \\s -> s\n"
  "export function encode (s) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return btoa(str.toUtf8(s));\n"
  "}\n"
  "\n"
  "// \\<bytes> -> s\n"
  "export function encodeBytes (Bs) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  const r = [];\n"
  "  for (let i = 0; i < Bs.length; ++i) r.push(String.fromCharCode(Bs[i]));\n"
  "  return btoa(r.join(\"\"));\n"
  "}\n"
  "\n"
  "// \\s -> s\n"
  "export function decode (s) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return str.fromUtf8(atob(s));\n"
  "}\n"
  "\n"
  "// \\s -> <bytes>\n"
  "export function decodeBytes (s) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  const tmp = atob(s);\n"
  "  const r = [];\n"
  "  r.length = tmp.length;\n"
  "  for (let i = 0; i < r.length; ++i) r[i] = tmp.charCodeAt(i);\n"
  "  return new Uint8Array(r);\n"
  "}\n"
  "\n"
;}
