// Copyright 11-Jul-2023 ºDeme
// GNU General Public License - V3 <http://www.gnu.org/licenses/>

char *bytes_bget (void) {return
  "// Copyright 17-Apr-2023 ºDeme\n"
  "// GNU General Public License - V3 <http://www.gnu.org/licenses/>\n"
  "\n"
  "/// Uint8Array\n"
  "\n"
  "import * as sys from './sys.js';\n"
  "import * as str from './str.js';\n"
  "\n"
  "// \\<bytes>, <bytes> -> <bytes>\n"
  "export function add (bs1, bs2) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  const bs = new Uint8Array(bs1.length + bs2.length);\n"
  "  bs.set(bs1, 0);\n"
  "  bs.set(bs2, bs1.length);\n"
  "  return bs;\n"
  "}\n"
  "\n"
  "// \\a, n -> a\n"
  "export function drop (bs, n) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  if (n < 0) n = 0;\n"
  "  return bs.slice(n);\n"
  "}\n"
  "\n"
  "// \\[n...] -> <bytes>\n"
  "export function fromArr (a) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return new Uint8Array(a);\n"
  "}\n"
  "\n"
  "// \\s -> <bytes>\n"
  "export function fromStr (s) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  const r = [];\n"
  "  for (const ch of str.toUtf8(s)) r.push(ch.codePointAt(0));\n"
  "  return new Uint8Array(r);\n"
  "}\n"
  "\n"
  "// \\n -> <bytes>\n"
  "export function mk (n) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  if (n < 0) n = 0;\n"
  "  return new Uint8Array(n)\n"
  "}\n"
  "\n"
  "// \\<bytes> -> n\n"
  "export function size (bs) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return bs.length;\n"
  "}\n"
  "\n"
  "// \\a, n -> a\n"
  "export function take (bs, n) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  if (n < 0) n = 0;\n"
  "  return bs.slice(0, n);\n"
  "}\n"
  "\n"
  "// \\<bytes> -> s\n"
  "export function toArr (bs) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  const r = [];\n"
  "  r.length = bs.length;\n"
  "  for (let i = 0; i < bs.length; ++i) r[i] = bs[i];\n"
  "  return r;\n"
  "}\n"
  "\n"
  "// \\<bytes> -> s\n"
  "export function toStr (bs) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  const r = [];\n"
  "  bs.forEach(e => r.push(String.fromCodePoint(e)));\n"
  "  return str.fromUtf8(r.join(''));\n"
  "}\n"
  "\n"
;}
