// Copyright 04-Nov-2025 ºDeme
// GNU General Public License - V3 <http://www.gnu.org/licenses/>

char *domo_bget (void) {return
  "// Copyright 03-May-2023 ºDeme\n"
  "// GNU General Public License - V3 <http://www.gnu.org/licenses/>\n"
  "\n"
  "import * as sys from './sys.js';\n"
  "\n"
  "class Domo {\n"
  "  constructor (e) {\n"
  "    this.el = e;\n"
  "  }\n"
  "  // \\<domo> -> <domo>\n"
  "  add (o) { this.el.appendChild(o.e); return this; }\n"
  "  // \\[<domo>] -> <domo>\n"
  "  adds (a) { for (const o of a) this.el.appendChild(o.e); return this; }\n"
  "  // \\s, * -> <domo>\n"
  "  att (k, v) { this.el.setAttribute(k, v); return this; }\n"
  "  // \\b -> <domo>\n"
  "  checked (v) { this.el.checked = v; return this; }\n"
  "  // \\b -> <domo>\n"
  "  disabled (v) { this.el.disabled = v; return this; }\n"
  "  // \\s -> *\n"
  "  getAtt (k) { return this.el.getAttribute(k) }\n"
  "  // \\-> s\n"
  "  getClass () { return this.el.className }\n"
  "  // \\-> s\n"
  "  getHtml () { return this.el.innerHTML }\n"
  "  // \\-> s\n"
  "  getStyle () { return this.el.getAttribute(\"style\") }\n"
  "  // \\-> s\n"
  "  getText () { return this.el.textContent }\n"
  "  // \\-> *\n"
  "  getValue () { return this.el.value }\n"
  "  // DOM element.\n"
  "  // *\n"
  "  get e() { return this.el; }\n"
  "  // \\s -> <domo>\n"
  "  html (s) { this.el.innerHTML = s; return this; }\n"
  "  // \\-> b\n"
  "  isChecked () { return this.el.checked }\n"
  "  // \\-> b\n"
  "  isDisabled () { return this.el.disabled }\n"
  "  // \\s -> <domo>\n"
  "  klass (s) { this.el.className = s; return this; }\n"
  "  // Type is one of:\n"
  "  // \"blur\"; \"change\"; \"click\"; \"dblclick\"; \"focus\"; \"input\";\n"
  "  // \"keydown\"; \"keypress\"; \"keyup\"; \"load\";\n"
  "  // \"mousedown\"; \"mousemove\"; \"mouseout\"; \"mouseover\"; \"mouseup\"; \"wheel\";\n"
  "  // \"select\"; \"selectstart\"; \"submit\"\n"
  "  // \\s, (\\->() | \\<event>->()) -> <domo>\n"
  "  on (type, fn) { this.el.addEventListener(type, fn, false); return this; }\n"
  "  // <domo> -> <domo>\n"
  "  remove (o) { this.el.removeChild(o.e); return this; }\n"
  "  // \\-> <domo>\n"
  "  removeAll () { this.el.innerHTML = \"\"; return this; }\n"
  "  // \\s, s-> <domo>\n"
  "  setStyle (k, v) { this.el.style.setProperty(k, v); return this; }\n"
  "  // \\s-> <domo>\n"
  "  style (v) { this.el.setAttribute(\"style\", v); return this; }\n"
  "  // \\s -> <domo>\n"
  "  text (s) { this.el.textContent = s; return this; }\n"
  "  // \\* -> <domo>\n"
  "  value (v) { this.el.value = v; return this; }\n"
  "}\n"
  "\n"
  "// \\* -> <domo>\n"
  "export function mk (e) {\n"
  "  return new Domo(e);\n"
  "}\n"
  "\n"
;}
