// Copyright 25-Apr-2024 ºDeme
// GNU General Public License - V3 <http://www.gnu.org/licenses/>

char *math_bget (void) {return
  "// Copyright 01-May-2023 ºDeme\n"
  "// GNU General Public License - V3 <http://www.gnu.org/licenses/>\n"
  "\n"
  "import * as sys from './sys.js';\n"
  "\n"
  "// \\n, n, n -> b\n"
  "export function eq (n1, n2, gap) {\n"
  "  sys.$params(arguments.length, 3);\n"
  "  return n1 + gap >= n2 && n1 - gap <= n2;\n"
  "}\n"
  "\n"
  "// \\s -> [n]|[]\n"
  "export function fromEn (n) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return fromStr(n.replace(\",\", \"\"));\n"
  "}\n"
  "\n"
  "// \\s -> [n]|[]\n"
  "export function fromHex (n) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  const n2 = n.toUpperCase();\n"
  "  for (let i = 0; i < n2.length; +i++) {\n"
  "    const ch = n2.charAt(i);\n"
  "    if (!((ch >= \"0\" && ch <= \"9\") || (ch >= \"A\" && ch <= \"F\"))) return [];\n"
  "  }\n"
  "  return [parseInt(n2, 16)];\n"
  "}\n"
  "\n"
  "// \\s -> [n]|[]\n"
  "export function fromIso (n) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return fromStr(n.replace(\".\", \"\").replace(\",\", \".\"));\n"
  "}\n"
  "\n"
  "// \\s -> [n]|[]\n"
  "export function fromStr (n) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  const v = parseFloat(n);\n"
  "  if (isNaN(v) || v === Infinity || v === -Infinity) return [];\n"
  "  return [v];\n"
  "}\n"
  "\n"
  "// \\s -> b\n"
  "export function isDigits (n) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  for (let i = 0; i < n.length; +i++) {\n"
  "    const ch = n.charAt(i);\n"
  "    if (!((ch >= \"0\" && ch <= \"9\"))) return false;\n"
  "  }\n"
  "  return true;\n"
  "}\n"
  "\n"
  "// \\ -> n\n"
  "export function rnd () {\n"
  "  sys.$params(arguments.length, 0);\n"
  "  return Math.random();\n"
  "}\n"
  "\n"
  "// \\n -> n\n"
  "export function rndi (top) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return Math.trunc(Math.random() * Math.trunc(top));\n"
  "}\n"
  "\n"
  "// \\n, n -> n\n"
  "export function round (n, dec) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  function fpow (v) {\n"
  "    switch (v) {\n"
  "      case 2: return 100;\n"
  "      case 0: return 1;\n"
  "      case 1: return 10;\n"
  "      case 3: return 1000;\n"
  "      case 4: return 10000;\n"
  "      case 5: return 100000;\n"
  "      case 6: return 1000000;\n"
  "      case 7: return 10000000;\n"
  "      case 8: return 100000000;\n"
  "      default: return 1000000000;\n"
  "    }\n"
  "  }\n"
  "  if (dec < 0) dec = 0;\n"
  "  else if (dec > 9) dec = 9;\n"
  "  const mul = fpow(dec);\n"
  "  if (n >= 0)\n"
  "    return Math.round(n * mul + 0.000000001) / mul;\n"
  "  return Math.round(n * mul - 0.000000001) / mul;\n"
  "}\n"
  "\n"
  "function to (n, dec, thsep, decsep) {\n"
  "  const ps = toFix(n, dec).split(\".\");\n"
  "  var ps0 = ps[0];\n"
  "  var sign = \"\";\n"
  "  if (ps0.charAt(0) == \"-\") {\n"
  "    ps0 = ps0.substring(1);\n"
  "    sign = \"-\";\n"
  "  }\n"
  "  const r0Length = ps0.length;\n"
  "  const r0 = [...ps0].reverse();\n"
  "  let r1 = [];\n"
  "  let i = 0;\n"
  "  while (true) {\n"
  "    r1.push(r0[i]);\n"
  "    ++i;\n"
  "    if (i >= r0Length) break;\n"
  "    if (i % 3 == 0) r1.push(thsep);\n"
  "  }\n"
  "  return sign + (ps.length == 1\n"
  "    ? r1.reverse().join(\"\")\n"
  "    : r1.reverse().join(\"\") + decsep + ps[1])\n"
  "  ;\n"
  "}\n"
  "\n"
  "// \\n, n -> s\n"
  "export function toEn (n, dec) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  return to(n, dec, \",\", \".\");\n"
  "}\n"
  "\n"
  "// \\n, n -> s\n"
  "export function toFix (n, dec) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  function pad (s, n) {\n"
  "    while (s.length < n) s += \"0\";\n"
  "    return s;\n"
  "  }\n"
  "\n"
  "  if (n === -0) n = 0;\n"
  "  const r1 = \"\" + round(n, dec);\n"
  "  const ps = r1.split(\".\");\n"
  "  if (ps.length == 1)\n"
  "    return dec == 0 ? ps[0] : ps[0] + \".\" + pad(\"\", dec);\n"
  "  return ps[0] + \".\" + pad(ps[1].substring(0, dec), dec);\n"
  "}\n"
  "\n"
  "// \\n -> s\n"
  "export function toHex (n) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return n.toString(16);\n"
  "}\n"
  "\n"
  "// \\n, n -> s\n"
  "export function toHexFix (n, dec) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  let r = n.toString(16);\n"
  "  while (r.length < dec) r = \"0\" + r;\n"
  "  return r;\n"
  "}\n"
  "\n"
  "// \\n -> n\n"
  "export function toInt (n) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return Math.trunc(n);\n"
  "}\n"
  "\n"
  "// \\n, n -> s\n"
  "export function toIso(n, dec) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  return to(n, dec, \".\", \",\");\n"
  "}\n"
  "\n"
  "// \\n -> s\n"
  "export function toStr(n) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  if (n === -0) n = 0;\n"
  "  return \"\" + n;\n"
  "}\n"
  "\n"
  "\n"
;}
