// Copyright 25-Apr-2024 ºDeme
// GNU General Public License - V3 <http://www.gnu.org/licenses/>

char *time_bget (void) {return
  "// Copyright 02-May-2023 ºDeme\n"
  "// GNU General Public License - V3 <http://www.gnu.org/licenses/>\n"
  "\n"
  "import * as sys from './sys.js';\n"
  "import * as math from './math.js';\n"
  "\n"
  "// \\n, n -> n\n"
  "export function addDays (t, n) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  const dt = new Date(t);\n"
  "  dt.setDate(dt.getDate() + n)\n"
  "  return dt.getTime();\n"
  "}\n"
  "\n"
  "// \\n -> n\n"
  "export function day (t) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return new Date(t).getDate();\n"
  "}\n"
  "\n"
  "// \\n, n -> n\n"
  "export function dfDays (t1, t2) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  const df = Math.trunc((t1 / 86400000) - (t2 / 86400000));\n"
  "  const t1b = addDays(t2, df);\n"
  "  return day(t1b) != day(t1)\n"
  "    ? t1b > t1 ? df + 1 : df - 1\n"
  "    : df\n"
  "  ;\n"
  "}\n"
  "\n"
  "// \\n, n -> b\n"
  "export function eqDay (t1, t2) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  return dfDays(t1, t2) === 0;\n"
  "}\n"
  "\n"
  "// \\n, s -> s\n"
  "export function format (t, template) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "\n"
  "  function f2 (n) {\n"
  "    const s = \"\" + n;\n"
  "    return s.length === 2 ? s : \"0\" + s;\n"
  "  }\n"
  "\n"
  "  if (template.length === 0) return \"\";\n"
  "\n"
  "  let dt = new Date(t);\n"
  "  let p = 0;\n"
  "  let r = [];\n"
  "  while (true) {\n"
  "    const p2 = template.indexOf(\"%\", p);\n"
  "    if (p2 === -1) break;\n"
  "\n"
  "    r.push(template.substring(p, p2));\n"
  "    p = p2 + 1;\n"
  "\n"
  "    if (p === t.length) throw new Error(\"Template ends at '%'\");\n"
  "    const ch = template.charAt(p);\n"
  "    switch (ch) {\n"
  "      case \"%\":\n"
  "        r.push(\"%\");\n"
  "        break;\n"
  "      case \"d\":\n"
  "        r.push(dt.getDate());\n"
  "        break;\n"
  "      case \"D\":\n"
  "        r.push(f2(dt.getDate()));\n"
  "        break;\n"
  "      case \"m\":\n"
  "        r.push(dt.getMonth() + 1);\n"
  "        break;\n"
  "      case \"M\":\n"
  "        r.push(f2(dt.getMonth() + 1));\n"
  "        break;\n"
  "      case \"y\":\n"
  "        r.push(dt.toISOString().substring(2, 4));\n"
  "        break;\n"
  "      case \"Y\":\n"
  "        r.push(dt.toISOString().substring(0, 4));\n"
  "        break;\n"
  "      case \"t\":\n"
  "        r.push(\n"
  "          f2(dt.getHours()) + \":\" +\n"
  "          f2(dt.getMinutes()) + \":\" +\n"
  "          f2(dt.getSeconds())\n"
  "        );\n"
  "        break;\n"
  "      case \"T\":\n"
  "        r.push(\n"
  "          f2(dt.getHours()) + \":\" +\n"
  "          f2(dt.getMinutes()) + \":\" +\n"
  "          f2(dt.getSeconds()) + \".\" +\n"
  "          dt.getMilliseconds()\n"
  "        );\n"
  "        break;\n"
  "      default:\n"
  "        throw new Error(\"Character after '%' (\" + ch + \") is not valid\");\n"
  "    }\n"
  "    ++p;\n"
  "  }\n"
  "\n"
  "  r.push(template.substring(p));\n"
  "  return r.join(\"\");\n"
  "}\n"
  "\n"
  "// \\n, s -> [n] | []\n"
  "export function fromClock (t1, s) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  if (s.charAt(2) !== \":\" || s.charAt(5) !== \":\") return [];\n"
  "  s = s.substring(0, 2) + s.substring(3,5) + s.substring(6);\n"
  "  if (!math.isDigits(s) || s.length != 6) return [];\n"
  "  const h = s.substring(0, 2)|0;\n"
  "  const m = s.substring(2, 4)|0;\n"
  "  const sec = s.substring(4)|0;\n"
  "  if (h > 23 || m > 59 || sec > 59) return [];\n"
  "  const dt = new Date(t1);\n"
  "  dt.setHours(h);\n"
  "  dt.setMinutes(m);\n"
  "  dt.setSeconds(sec);\n"
  "  dt.setMilliseconds(0);\n"
  "  return [dt.getTime()];\n"
  "}\n"
  "\n"
  "// \\<Date> -> n\n"
  "export function fromDate (d) {\n"
  "  return d.getTime();\n"
  "}\n"
  "\n"
  "// \\s, s -> [n] | []\n"
  "export function fromEn (s, sep) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  if (s.charAt(2) !== sep.charAt(0) || s.charAt(5) !== sep.charAt(0)) return [];\n"
  "  s = s.substring(6) + s.substring(0, 2) + s.substring(3,5);\n"
  "  return fromStr(s);\n"
  "}\n"
  "\n"
  "// \\s, s -> [n] | []\n"
  "export function fromIso (s, sep) {\n"
  "  sys.$params(arguments.length, 2);\n"
  "  if (s.charAt(2) !== sep.charAt(0) || s.charAt(5) !== sep.charAt(0)) return [];\n"
  "  s = s.substring(6) + s.substring(3, 5) + s.substring(0, 2);\n"
  "  return fromStr(s);\n"
  "}\n"
  "\n"
  "// \\s -> [n] | []\n"
  "export function fromStr (s) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  if (!math.isDigits(s) || s.length != 8) return [];\n"
  "  const y = s.substring(0, 4)|0;\n"
  "  const m = s.substring(4, 6)|0;\n"
  "  const d = s.substring(6)|0;\n"
  "  return [new Date(y, m - 1, d, 12).getTime()];\n"
  "}\n"
  "\n"
  "// \\n -> n\n"
  "export function hour (t) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return new Date(t).getHours();\n"
  "}\n"
  "\n"
  "// \\n -> n\n"
  "export function minute (t) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return new Date(t).getMinutes();\n"
  "}\n"
  "\n"
  "// \\n -> n\n"
  "export function millisecond (t) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return new Date(t).getMilliseconds();\n"
  "}\n"
  "\n"
  "// \\n -> n\n"
  "export function month (t) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return new Date(t).getMonth() + 1;\n"
  "}\n"
  "\n"
  "// \\n, n, n, n, n, n -> n\n"
  "export function mk (day, month, year, hour, minute, second) {\n"
  "  sys.$params(arguments.length, 6);\n"
  "  return new Date(year, month - 1, day, hour, minute, second).getTime();\n"
  "}\n"
  "\n"
  "// \\n, n, n -> n\n"
  "export function mkDate (day, month, year) {\n"
  "  sys.$params(arguments.length, 3);\n"
  "  return new Date(year, month - 1, day, 12).getTime();\n"
  "}\n"
  "\n"
  "// \\-> n\n"
  "export function now () {\n"
  "  sys.$params(arguments.length, 0);\n"
  "  return new Date().getTime();\n"
  "}\n"
  "\n"
  "// \\n -> n\n"
  "export function second (t) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return new Date(t).getSeconds();\n"
  "}\n"
  "\n"
  "// \\n -> <Date>\n"
  "export function toDate (t) {\n"
  "  return new Date(t);\n"
  "}\n"
  "\n"
  "// \\n -> s\n"
  "export function toEn (t) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return format(t, \"%M-%D-%Y\");\n"
  "}\n"
  "\n"
  "// \\n -> s\n"
  "export function toIso (t) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return format(t, \"%D/%M/%Y\");\n"
  "}\n"
  "\n"
  "// \\n -> s\n"
  "export function toStr (t) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return format(t, \"%Y%M%D\");\n"
  "}\n"
  "\n"
  "// \\n -> n\n"
  "export function weekday (t) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return new Date(t).getDay();\n"
  "}\n"
  "\n"
  "// \\n -> n\n"
  "export function year (t) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  return new Date(t).getFullYear();\n"
  "}\n"
  "\n"
  "// \\n -> n\n"
  "export function yearDay (t) {\n"
  "  sys.$params(arguments.length, 1);\n"
  "  const dt = new Date(t);\n"
  "  return Math.floor((dt - new Date(dt.getFullYear(), 0, 0)) / 86400000);\n"
  "}\n"
  "\n"
  "\n"
  "\n"
;}
