// Copyright 22-Mar-2025 ºDeme
// GNU General Public License - V3 <http://www.gnu.org/licenses/>

#include "DEFS.h"
#include "comp/compiler.h"
#include "kut/map.h"
#include "kut/path.h"
#include "kut/file.h"
#include "kut/rs.h"
#include "kut/js.h"
#include "data/module.h"
#include "data/imp.h"
#include "data/tp.h"
#include "data/tp3.h"
#include "comp/ogrouping.h"
#include "comp/bwriter.h"
#include "comp/hwriter.h"
#include "comp/cmd.h"
#include "modules.h"
#include "cts.h"
#include "db.h"

// mds is Arr<Module>
// g is Arr<char>
static char *compile_module(char *header, Module *m) {
  char *md_id = m->id;

  Tp *tp = bwriter_write(m);
  char *error = tp->e1;
  if (*error) return error;
  char *ccode = tp->e2;

  char *cmain = "";
  if (m->is_main)
    cmain = str_replace(str_replace(
      "//\n"
      "// MAIN ------------------------------------------------------------------------\n"
      "//\n"
      "int main (int argc, char **argv) {\n"
      "  __sys_init(argc, argv, {COMPILER_ROOT});\n"
      "  TRY\n"
      "   {MODULE}_main();\n"
      "  CATCH(e)\n"
      "    puts(exc_msg(e));\n"
      "    EACH(exc_stack(e), char, l)\n"
      "      char *lktt = ___built_stack_line(l);\n"
      "      if (*lktt) printf(\"  %s\\n\", lktt);\n"
      "    _EACH\n"
      "  _TRY\n"
      "  return 0;\n"
      "}\n",
      "{COMPILER_ROOT}", js_ws(cts_data_path())), "{MODULE}", m->id)
    ;

  char *code = str_f(
    "// Generated by kutt (%s)\n"
    "%s"
    "\n//\n// BODY "
    "------------------------------------------------------------------------"
    "\n//\n"
    "%s\n%s",
    time_to_str(time_now()), header, ccode, cmain
  );

  char *cfile =
    path_cat(cts_compilation_path(), str_f("%s.c", md_id), NULL);
  file_write(cfile, code);
  char *ofile =
    path_cat(cts_compilation_path(), str_f("%s.o", md_id), NULL);

  Rs *rs = cmd_run(arr_new_from(
    "gcc", "-Wno-div-by-zero", "-c", "-rdynamic", "-z", "execstack",
    cfile, "-o", ofile, "-I", cts_data_path(), "-L", cts_data_path(),
    "-lbuilt", "-lgc", "-lm", "-lpthread", NULL
  ));
  if (!rs_get(rs)) return rs_error(rs);

  return "";
}

// done and todo are Arr<Module>
static char *compile_group(char *header, Arr *done, Arr *todo) {
  if (!arr_size(todo)) return "";
  Module *m = arr_pop(todo);
  char *m_id = m->id;
  EACH(done, Module, mdone) {
    if (!strcmp(m_id, mdone->id)) return compile_group(header, done, todo);
  }_EACH
  arr_push(done, m);

  void feach (Module *m2) {
    EACH(m2->imports, Kv, kv) {
      Imp *im = kv_value(kv);
      if (!strcmp(im->id, m_id)){
        arr_push(todo, m2);
        file_del(path_cat(cts_compilation_path(), str_f("%s.o", m->id), NULL));
        break;
      }
    }_EACH
  }
  modules_each(feach);

  char *err = compile_group(header, done, todo);
  if (*err) return err;

  return compile_module(header, m);
}

char *compiler_run (int only_compile) {
  // Arr<char>
  Arr *header_bf = arr_new();
  arr_push(header_bf, "#include \"../built.h\"");

  Module *mainm = NULL;
  void feach1 (Module *m) {
    char *hcode = hwriter_write(m);
    arr_push(header_bf, hcode);
    if (m->is_main) mainm = m;
  }
  modules_each(feach1);

  if (!mainm) EXC_KUTT("Main module not found");
  char *fexe = path_cat(cts_compilation_path(), str_f("%s.bin", mainm->id), NULL);
  char *header = arr_cjoin(header_bf, '\n');

  // Arr<char>
  Arr *fos = arr_new();
  // Arr<char>
  Arr *errs = arr_new();
  void feach2 (Module *m) {
    char *kpath = m->path;
    char *opath = path_cat(cts_compilation_path(), str_f("%s.o", m->id), NULL);
    arr_push(fos, opath);

    if (!file_exists(opath) || file_modified(kpath) > file_modified(opath)) {
      // Arr<Module>
      Arr *done = arr_new();
      // Arr<Module>
      Arr *todo = arr_new();
      arr_push(todo, m);
      char *err = compile_group(header, done, todo);
      if (*err) arr_push(errs, err);
    }
  }
  modules_each(feach2);
  if (arr_size(errs)) return *arr_begin(errs);

  if (only_compile) return "";

  Arr *cm = arr_new_from(
    "gcc", "-Wno-div-by-zero", "-Wmain", "-rdynamic", "-z", "execstack", NULL
  );
  arr_cat(cm, fos);
  arr_cat(cm, arr_new_from(
    "-o", fexe, "-L", cts_data_path(),
    "-lbuilt", "-lgc", "-lm", "-lpthread", NULL
  ));

  Rs *rs = cmd_run(cm);
  if (!rs_get(rs)) return rs_error(rs);

  return "";
}
